# Generated by Django 4.2.7 on 2024-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
