# Generated by Django 4.2.7 on 2024-02-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregapp', '0003_userregistermodel_delete_userregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistermodel',
            name='user',
        ),
    ]
