# Generated by Django 4.2.7 on 2024-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregapp', '0005_alter_userregistermodel_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='ConfirmPassword',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='Fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='Location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='NIN',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='Password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='Skill',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
